site_name: Fleex
site_url: https://github.com/sw33tLie/fleex-docs
theme:
  logo: img/fleex_white.png
  favicon: img/fleex_white.png
  features:
    - navigation.tabs
    - navigation.expand
  name: material
  # custom_dir: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: deep-purple
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  
extra_css:
  - stylesheets/extra.css

nav:
  # - Home: index.md
  - Getting started:
    - introduction: get-started/index.md
    - Installation: get-started/install.md
    - Configuration: get-started/config.md
    - Commands:
      - build: commands/build.md
      - config: commands/config.md
      - delete: commands/delete.md
      - images: commands/images.md
      - ls: commands/ls.md
      - run: commands/run.md
      - scan: commands/scan.md
      - scp: commands/scp.md
      - spawn: commands/spawn.md
      - ssh: commands/ssh.md
    - Providers:
      - linode: get-started/linode.md
      - digitalocean: get-started/digitalocean.md
    # - Images: get-started/images.md
    # - Boxes: get-started/boxes.md
    # - Distributed commands: get-started/commands.md
  - FAQ:
    - faq: faq/faq.md
   
  - Changelog:
    - Fleex: releases.md
  - Credits:
    - Contributors: credits.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.superfences
  - admonition
  - attr_list
  - pymdownx.tabbed

repo_url: https://github.com/sw33tLie/fleex
repo_name: Fleex

copyright: Apache Licence &copy xm1k3 / sw33tLie