site_name: Fleex
site_url: https://example.com/
theme:
  features:
    - navigation.tabs
    - navigation.expand
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

nav:
  - Getting started:
    - index: index.md
    - install: install.md
  - Configuration:
    - index: config/index.md
    - Providers:
      - linode: config/linode.md
      - digitalocean: config/digitalocean.md
  - Changelog:
    - Fleex: releases.md
  - Credits:
    - Contributors: credits.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.superfences
  - admonition
  - attr_list

repo_url: https://github.com/sw33tLie/fleex
repo_name: Fleex

copyright: Apache Licence &copy xm1k3 / sw33tLie
